modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
issueTrackerURL="https://github.com/fallOut015/two.src/issues" #optional
[[mods]]
modId="two"
version="${file.jarVersion}"
displayName="Minecraft v2.0"
updateJSONURL="https://fallout015.github.io/two.src/updateJSONURL.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-v2" #optional
logoFile="two.png" #optional
credits="Well, me, HarryTalks, other tutorial youtubers, Forge guys, Notch, Jeb, Derek, Karsten, Pam, my friends, among others. OrionSh. humanoidZX. NoName. Jägermeister Patrons:" #optional
authors="fallOut015" #optional
description='''
Minecraft just got an upgrade. 
Changelog:
	Added battleaxes.
	Added wooden armor.
	Added stone armor.
	Added woolen clothes.
	Added sponge armor.
	Added chainmail horse armor.
	Added emerald tools and weapons.
	Added sickles.
	Added stained planks.
	Added glazed bricks.
	Added chameleons.
	Added artifact weapons.
	Added new wood.
	Added backpacks.
	Added new splashes.
	Added dreamcatchers.
	Added the Nightmare Dimension.
	Added decorative iron blocks.
	Added the Billboard block.
	Added Adobe blocks.
	Added new ores.
	Added the upholstery table, for furniture.
	Added chairs.
	Added stools.
	Added capped arrows.
	Added the Staff of Evocation.
	Added Nidavellir.
	Added Regolith and Myrkylite.
	Added letters and numbers.
	Added daggers. 
	Added a handful of new enchantments. 
	Added food scraps. 
	Added extra textures for weapon durability. 
	Added a stupid placeholder title. 
	Added extra health when the player levels up (will change in the future).
	Added the ground light. 
	Added fire arrows. 
	Added ice arrows. 
	Added bomb arrows.
	Added shock arrows.
	Added caverns. 
	Changed some underground generations. 
	Added the Mummified Zombie. 
	Added the Succulight cactus. 
	Added flagstone path. 
	Added some new ore variations. 
	Added copper items.
	Added Ability Enchantments. 
	Added Ice Slimes. 
	Added the Ice Slime Block. 
	Added the Hermes Helmet. 
	Added the Neondot and Brimshine mushrooms.
	Added the Shroomlight Lantern. 
	Added the Chameleon Cloak. 
	Added the Slime Boots.
	Added the Beaming Boots.
	Added a configuration file.
'''
[[dependencies.examplemod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
