modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="two"
version="${file.jarVersion}"
displayName="NEW Minecraft v2"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-v2" #optional
logoFile="two.png" #optional
credits="Well, me, HarryTalks, other tutorial youtubers, Forge guys, Notch, Jeb, Derek, Karsten, Pam, my friends, among others. OrionSh. Patrons:" #optional
authors="fallOut015" #optional
description='''
Minecraft just got an upgrade. 
Changelog:
	Added battleaxes.
	Added wooden armor.
	Added stone armor.
	Added woolen clothes.
	Added sponge armor.
	Added chainmail horse armor.
	Added emerald tools and weapons.
	Added sickles.
	Added stained planks.
	Added glazed bricks.
	Added chameleons.
	Added artifact weapons.
	Added new wood.
	Added backpacks.
	Added new splashes.
	Added dreamcatchers.
	Added the Nightmare Dimension.
	Added decorative iron blocks.
	Added the Billboard block.
	Added Adobe blocks.
	Added new ores.
	Added the upholstery table, for furniture.
	Added chairs.
	Added stools.
	Added capped arrows.
	Added the Staff of Evocation.
	Added Nidavellir.
	Added Regolith and Myrkylite.
	Added letters and numbers.
	Added daggers. 
	Added a handful of new enchantments. 
	Added food scraps. 
	Added extra textures for weapon durability. 
	Added a stupid placeholder title. 
	Added extra health when the player levels up (will change in the future).
	Added the ground light. 
'''
[[dependencies.two]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.two]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"