modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="two" #mandatory
version="${file.jarVersion}" #mandatory
displayName="NEW Minecraft v2" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="two.png" #optional
credits="Well, me, HarryTalks, other tutorial youtubers, Forge guys, Notch, Jeb, Derek, Karsten, Pam, my friends, among others." #optional
authors="fallOut015" #optional
description='''
Minecraft just got an upgrade. 
Changelog:
	Added battleaxes.
	Added wooden armor.
	Added stone armor.
	Added woolen clothes.
	Added chainmail horse armor.
	Added emerald tools and weapons.
	Added sickles.
	Added stained planks.
	Added glazed bricks.
	Added chameleons.
	Added artifact weapons.
	Added cherry wood.
	Added maple wood.
	Added backpacks.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"